// USER
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const LoginTypes = {
    GOOGLE_START: "GOOGLE_START",
    OK: "OK",
    FAILURE: "FAILURE",
    EMAIL_START: "EMAIL_START",
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
}

// CART AND SHOP

export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN"
export const ADD_ITEM = "ADD_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART"
export const CLEAR_CART = 'CLEAR_CART'


export const FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START"
export const FETCH_COLLECTIONS_SUCCESS= "FETCH_COLLECTIONS_SUCCESS"
export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE"
