// USER
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const LoginTypes = {
    GOOGLE_START: "GOOGLE_START",
    GOOGLE_OK: "GOOGLE_OK",
    GOOGLE_FAILURE: "GOOGLE_FAILURE",
    EMAIL_START: "EMAIL_START",
    EMAIL_OK: "EMAIL_OK",
    EMAIL_FAILURE: "EMAIL_FAILURE"
}

// CART AND SHOP

export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN"
export const ADD_ITEM = "ADD_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART"

export const FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START"
export const FETCH_COLLECTIONS_SUCCESS= "FETCH_COLLECTIONS_SUCCESS"
export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE"
